services:
  db:
    image: mysql:5.7
    container_name: bazasql
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./env/mysql.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./db:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
    container_name: wordp
    ports:
      - "8222:80"
    restart: always
    depends_on:
      - db
    env_file:
      - ./env/wordpress.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./wordpress:/var/www/html 
    networks:
      - wordpress_network 

  
networks:
  wordpress_network:

volumes:
  wordp:
  bazasql:

